/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package flink4k

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test
    fun `name and id set up correctly`() {
        assertTrue(true, "someLibraryMethod should return 'true'")
    }
}
